### PR TITLE
ReceivedPaymentsRepo

### PR DESCRIPTION
**Pull request by apereverzin**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSBPS-753

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by mdayican — COMMENTED** [review]
why do you need this endpoint?

**Comment by apereverzin** [comment]
It is similar to scannable documents. Some people consider payments a type of scannable documents and need statistics for both scannable documents and payments

**Comment by mdayican** [comment]
> It is similar to scannable documents. Some people consider payments a type of scannable documents and need statistics for both scannable documents and payments

I think we can not add all these reports as endpoint .
May be we need unprocessed payment details.

**Review by mdayican — APPROVED** [review]
unprocessed payment details  would be more useful.

**Pull request merged**
