### PR TITLE
Updated Dirties context

### PR DESCRIPTION
**Pull request by apereverzin**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSBPS-610

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by mdayican — COMMENTED** [review]
I can not see which test is failing.
but if this test case is failing this change does not fix it as it deletes after this test.

**Comment by apereverzin** [comment]
The failing test is here: https://build.platform.hmcts.net/view/BSP/job/HMCTS_BSP/job/bulk-scan-processor/job/master/840/console (the link is in the task). There are more results than expected and I assume this is because some records were not deleted from db.

**Review by mdayican — COMMENTED** [review]
have you checked the other test classes?

**Comment by apereverzin** [comment]
I am planning to make similar changes in other classes in a new PR. There are 4 more classes with
`@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)`
and I am planning to change all of them to 
`@DirtiesContext(methodMode = DirtiesContext.MethodMode.BEFORE_METHOD)`
Or doing this in this PR is better?

**Comment by mdayican** [comment]
> I am planning to make similar changes in other classes in a new PR. There are 4 more classes with
> `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)`
> and I am planning to change all of them to
> `@DirtiesContext(methodMode = DirtiesContext.MethodMode.BEFORE_METHOD)`
> Or doing this in this PR is better?

It think this PR is good place to do.

**Review by mdayican — APPROVED** [review]

**Comment by apereverzin** [comment]
PR-1949

**Pull request closed without merging**
